version: '3'
services:
  mydb:
    image: mysql:latest
    container_name: mysql-docker-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'doodle'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'

    volumes:
      - my-db:/var/lib/mysql

    ports:
      - 3306:3306
    expose:
      - 3306

  server:
    build: .
    image: simba
    container_name: simbaProject
    restart: always
    links:
      - mydb:mydb
    environment:

      - DATABASE_HOST=mydb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=doodle
      - DATABASE_PORT=3306
    depends_on:
      - mydb
    ports : 
      - 8080:8080
 #   command: >
 #     /bin/sh -c "
 #       ./api-1.0-SNAPSHOT-runner -Dquarkus.http.host=0.0.0.0 -Dquarkus.datasource.url=mydb:5432
 #      "

    #entrypoint: ["./work/application/","-Dquarkus.http.host=0.0.0.0", "-Dquarkus.datasource.url=jdbc:postgresql://postgres:5432/simba", "-Djava.util.logging.manager=org.jboss.logmanager.LogManager"]
volumes:
  my-db:
      driver: local
   
  
    
    
    
    
    
    
